 services:
   backend:
     container_name: rowboat_backend
     build:
       context: ./back
       dockerfile: Dockerfile
     ports:
       - "8000:8000"
     volumes:
       - ./back:/app
     environment:
       - PYTHONUNBUFFERED=1
     command: fastapi dev app.py --host 0.0.0.0 --port 8000 --reload

   frontend:
     container_name: rowboat_frontend
     build:
       context: ./front/rowboat
       dockerfile: Dockerfile
     ports:
       - "3000:3000"
     volumes:
       - ./front/rowboat:/front

     command: npm run dev
