 services:
   backend:
     container_name: rowboat_backend
     build:
       context: ./back
       dockerfile: Dockerfile
     ports:
       - "8000:8000"
     volumes:
       - ./back:/back
     environment:
       - PYTHONUNBUFFERED=1
     command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

   frontend:
    #  network_mode: "host"
    #  environment:
    #   - NODE_ENV=development
     container_name: rowboat_frontend
     build:
       context: ./front/rowboat
       dockerfile: Dockerfile
     ports:
       - "3000:3000"
     volumes:
       - ./front/rowboat:/front
    #  working_dir: /front
    #  environment:
    # #   #  - RAYON_NUM_THREADS=1
    #    - RUST_BACKTRACE=full

     command: npm run dev
